Added VM to ostypes to indicate KVM virtual machines
erigones/esdc-docs pull request #4
Opened 2016-12-06 15:16 UTC by mbag

Please review and merge this PR. It is related to issue erigones/esdc-ce#1

2016-12-07 21:05 UTC, dn0 requested changes

2016-12-07 21:05 UTC, dn0 commented on user-guide/monitoring/vm_monitoring.rst
>      * ``{ostype_text}`` - The type of the operating system with lowercase letters and spaces replaced with underscores (*linux*, *sunos*, *bsd*, *windows*, *sunos_zone*).
The change in erigones/esdc-ce#1 also affects `vm.ostype_text()`, e.g. `bsd` will be `bsd_vm`

2016-12-07 21:05 UTC, dn0 commented on user-guide/monitoring/vm_monitoring.rst
>      * ``{ostype_text}`` - The type of the operating system with lowercase letters and spaces replaced with underscores (*linux*, *sunos*, *bsd*, *windows*, *sunos_zone*).
See comment above.

2016-12-08 08:51 UTC, mbag commented on user-guide/monitoring/vm_monitoring.rst
>      * ``{ostype_text}`` - The type of the operating system with lowercase letters and spaces replaced with underscores (*linux*, *sunos*, *bsd*, *windows*, *sunos_zone*).
Made changes in 75195cb9123b67a1711e9d44395746a3016eaf8a

2016-12-08 08:51 UTC, mbag commented on user-guide/monitoring/vm_monitoring.rst
>      * ``{ostype_text}`` - The type of the operating system with lowercase letters and spaces replaced with underscores (*linux*, *sunos*, *bsd*, *windows*, *sunos_zone*).
Made requested changes in 75195cb9123b67a1711e9d44395746a3016eaf8a

2016-12-08 08:54 UTC, dn0 approved these changes

2016-12-12 09:58 UTC, merged